name: Validate examples
on:
  push:
    paths:
      - "EXAMPLES/**"
      - "scripts/validate_examples.py"
      - ".github/workflows/validate.yml"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Run validators
        run: |
          python -m pip install --upgrade pip
          python scripts/validate_examples.py
